name: CI

on:
  push:
    branches:
      - main
      - rfs
  pull_request:

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install npm dependencies
        run: npm install

      - name: Lint Check
        run: make lint-check 

      - name: Gas snapshot check
        run: make snapshot
      
      - name: Run tests
        run: FOUNDRY_PROFILE=ci make test
